version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: izlecine-backend
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      - rabbitmq
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./movieapp-frontend
    container_name: izlecine-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
